### ISSUE TITLE
District P16 wrongly shows historical voting result of P17

### ISSUE THREAD

**Issue by henrywkk** [cswbrian/district-councils-dashboard#112]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?** *bug*

* **What is the current behavior?** district page P16 wrongly shows historical voting result of district P17

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  

1. go to https://vote4.hk/district/2019/P16
2. scroll down until you see "2015年 - 康樂園（P17）"

* **What is the expected behavior?** show historical voting result of district P16

* **What is the motivation / use case for changing the behavior?** Reflect the actual historical voting result of corresponding district

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all]
  - Language: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by cswbrian** [comment]
@henrywkk thanks for the report! I will take a look on that

**Comment by cswbrian** [comment]
Fixed
